databases:
  - name: social_media_db
    databaseName: social_media_db
    user: social_media_user

services:
  - type: web
    name: social-media-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
