# Generated by Django 5.2.5 on 2025-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="published_year",
            field=models.PositiveIntegerField(default=1990),
            preserve_default=False,
        ),
    ]
