# Generated by Django 4.2.19 on 2025-02-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_publication_date_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_year',
        ),
    ]
