# Generated by Django 4.2.19 on 2025-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='librarian',
            old_name='name',
            new_name='librarian_name',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='name',
            new_name='library_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
