# Generated by Django 4.2.19 on 2025-03-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_rename_name_author_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='librarian',
            old_name='librarian_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='library_name',
            new_name='name',
        ),
    ]
