# Generated by Django 4.2.19 on 2025-03-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_rename_name_library_library_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
