# Generated by Django 4.2.19 on 2025-03-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_rename_name_author_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='library_name',
            new_name='library',
        ),
    ]
