# Generated by Django 4.2.19 on 2025-03-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_rename_library_name_library_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='library',
            new_name='library_name',
        ),
    ]
