# Generated by Django 5.2.5 on 2025-09-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookshelf",
            "0002_alter_book_options_book_created_at_book_favorited_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("can_view", "Can view book"),
                    ("can_create", "Can create book"),
                    ("can_edit", "Can edit book"),
                    ("can_delete", "Can delete book"),
                ],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
